source :rubygems

group :test do
    gem 'calabash-android', '0.4.4'
    gem 'cucumber', '1.2.3'
    gem 'rspec-expectations', '2.13.0'
    gem 'activerecord', '3.2.13'
    gem 'pickle', '0.4.11'
    gem 'retriable', '1.3.3'
    gem 'httparty', '0.10.2'
    gem 'pry-nav', '0.2.3'
    gem 'sqlite3', '1.3.7'
    gem 'json', '~> 1.7.7'
end
